//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol _SBFakeBlurObserver;

@protocol _SBFakeBlur <NSObject>
@property(nonatomic) unsigned long long transformOptions;
@property(nonatomic) _Bool fullscreen;
@property(nonatomic) id <_SBFakeBlurObserver> observer;
- (void)offsetWallpaperBy:(struct CGPoint)arg1;
- (long long)effectiveStyle;
- (void)requestStyle:(long long)arg1;
@end

