//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UIDynamicItem-Protocol.h"

@class NSString, UIBezierPath;

@interface _SBNotificationCenterBouncingItem : NSObject <UIDynamicItem>
{
    struct CGPoint _center;
    struct CGRect _bounds;
    CDUnknownBlockType _stepper;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGRect frame;
@property(nonatomic) struct CGAffineTransform transform;
- (void)setBounds:(struct CGRect)arg1;
@property(readonly, nonatomic) struct CGRect bounds;
@property(nonatomic) struct CGPoint center;
- (id)initWithFrame:(struct CGRect)arg1 stepper:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, nonatomic) UIBezierPath *collisionBoundingPath;
@property(readonly, nonatomic) unsigned long long collisionBoundsType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

