//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CCUIControlCenterSettings, NCMaterialSettings, NSArray, NSString, NSURL;
@protocol CCUIStatusBarHidingAssertion;

@protocol CCUIControlCenterSystemAgent <NSObject>
- (id <CCUIStatusBarHidingAssertion>)hideStatusBarAssertion;
- (_Bool)isUILocked;
- (NSString *)frontmostApplicationDisplayID;
- (NSArray *)getFGSceneIdentifiers;
- (_Bool)wifiIsPowered;
- (_Bool)wifiDevicePresent;
- (void)setWifiPowered:(_Bool)arg1;
- (void)updateWifiDevicePresence;
- (_Bool)isInAirplaneMode;
- (_Bool)isOrientationLocked;
- (void)unlockOrientation;
- (void)lockOrientation;
- (_Bool)wirelessDisplayRouteIsPicked;
- (NSString *)nameOfPickedRoute;
- (_Bool)handsetRouteIsSelected;
- (void)setRingerMuted:(_Bool)arg1;
- (_Bool)isRingerMuted;
- (void)activateAppWithDisplayID:(NSString *)arg1 url:(NSURL *)arg2 unlockIfNecessary:(_Bool)arg3;
- (void)activateAppWithDisplayID:(NSString *)arg1 url:(NSURL *)arg2;
- (void)dismissAnimated:(_Bool)arg1 completion:(void (^)(void))arg2;
- (NCMaterialSettings *)materialSettings;
- (CCUIControlCenterSettings *)prototypeSettings;

@optional
- (void)promptForUnlockIfNecessary:(void (^)(_Bool))arg1;
@end

