//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBSceneHostManager, NSString;

@protocol FBSceneHostManagerDelegate <NSObject>

@optional
- (_Bool)sceneHostManager:(FBSceneHostManager *)arg1 shouldEnableHostingForRequester:(NSString *)arg2 priority:(long long)arg3;
- (NSString *)sceneHostManager:(FBSceneHostManager *)arg1 overrideRequester:(NSString *)arg2;
@end

