//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBUIApplicationService, NSDate, NSString;

@protocol FBUIApplicationServiceDelegate <NSObject>

@optional
- (void)applicationService:(FBUIApplicationService *)arg1 suspendApplicationWithBundleIdentifier:(NSString *)arg2;
- (void)applicationService:(FBUIApplicationService *)arg1 setNextWakeDate:(NSDate *)arg2 forBundleIdentifier:(NSString *)arg3;
- (void)applicationService:(FBUIApplicationService *)arg1 deleteAllSnapshotsForBundleIdentifier:(NSString *)arg2;
- (void)applicationService:(FBUIApplicationService *)arg1 getBadgeValueForBundleIdentifier:(NSString *)arg2 withCompletion:(void (^)(id))arg3;
- (void)applicationService:(FBUIApplicationService *)arg1 setBadgeValue:(id)arg2 forBundleIdentifier:(NSString *)arg3;
@end

