//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UserNotificationsKit/NCNotificationRequest.h>

@interface NCNotificationRequest (UserAlert)
+ (id)_notificationSoundFromSound:(id)arg1;
+ (id)_notificationOptionsForAlertItem:(id)arg1;
+ (id)_destinations;
+ (id)notificationRequestWithAlertItem:(id)arg1;
@end

