//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (CTHelpers)
- (id)callingNamePresentationValue;
- (struct __CFString *)settingType;
- (id)mmiProcedure;
- (id)ssServiceType;
- (id)serviceCenterAddress;
- (id)enabledString;
- (id)connectedLinePresentationValue;
- (id)connectedLineIDRestrictionValue;
- (id)callingLinePresentationValue;
- (id)callingLineIDRestrictionValue;
- (id)callBarringFacility;
- (id)callForwardingReason;
- (id)callClass;
@end

