//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableArray.h>

@interface NSMutableArray (SBQueueAdditions)
- (id)_sb_peek;
- (id)_sb_dequeue;
- (void)_sb_enqueue:(id)arg1;
@end

