//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBAlertWindowViewController;

@protocol SBAlertWindowViewControllerDelegate <NSObject>
- (unsigned long long)defaultSupportedInterfaceOrientationsForAlertWindowViewController:(SBAlertWindowViewController *)arg1;
- (long long)defaultInterfaceOrientationForPresentationOfAlertWindowViewController:(SBAlertWindowViewController *)arg1;
- (_Bool)defaultShouldAutorotateForAlertWindowViewController:(SBAlertWindowViewController *)arg1;
@end

