//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SBAppViewBackgroundView-Protocol.h"

@class NSString, SBWallpaperEffectView;

@interface SBAppViewBackgroundView : UIView <SBAppViewBackgroundView>
{
    long long _wallpaperStyle;
    SBWallpaperEffectView *_backgroundWallpaperEffectView;
}

@property(nonatomic) long long wallpaperStyle; // @synthesize wallpaperStyle=_wallpaperStyle;
- (void).cxx_destruct;
- (void)_teardownBackgroundWallpaperEffectView;
- (id)_backgroundWallpaperEffectView;
- (void)_setupBackground;
- (_Bool)_isTranslucent;
@property(readonly, copy) NSString *description;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

