//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBApplicationServerDelegate-Protocol.h"

@class NSString, SBApplicationServer;
@protocol FBSystemServiceClient;

@protocol SBApplicationServerRemovabilityDelegate <SBApplicationServerDelegate>
- (void)applicationServer:(SBApplicationServer *)arg1 client:(id <FBSystemServiceClient>)arg2 setRemovalAllowed:(_Bool)arg3 forBundleIdentifier:(NSString *)arg4;
- (void)applicationServer:(SBApplicationServer *)arg1 client:(id <FBSystemServiceClient>)arg2 fetchRemovabilityForBundleIdentifier:(NSString *)arg3 withCompletion:(void (^)(long long))arg4;
@end

