//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBLayoutElementContainerView.h"

@class SBAppView;

@interface SBAppContainerView : SBLayoutElementContainerView
{
    SBAppView *_appView;
}

- (void).cxx_destruct;
- (id)snapshotView;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)prepareForReuse;
- (void)setLayoutElementViewAlpha:(double)arg1;
- (unsigned long long)_supportedOrientations;
@property(retain, nonatomic) SBAppView *appView;
- (void)setDisplayMode:(long long)arg1;
- (long long)displayMode;

@end

