//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBApplicationServerDelegate-Protocol.h"

@class NSArray, NSString, SBApplicationServer;
@protocol FBSystemServiceClient;

@protocol SBApplicationServerCarPlayDelegate <SBApplicationServerDelegate>
- (void)applicationServer:(SBApplicationServer *)arg1 client:(id <FBSystemServiceClient>)arg2 fetchApplicationForBundleIdentifier:(NSString *)arg3 inVehicle:(NSString *)arg4 withCompletion:(void (^)(NSString *, UIImage *))arg5;
- (void)applicationServer:(SBApplicationServer *)arg1 client:(id <FBSystemServiceClient>)arg2 resetAppIdentifierOrderForVehicleId:(NSString *)arg3;
- (void)applicationServer:(SBApplicationServer *)arg1 client:(id <FBSystemServiceClient>)arg2 setIconOrder:(NSArray *)arg3 hiddenIcons:(NSArray *)arg4 forVehicleId:(NSString *)arg5;
- (void)applicationServer:(SBApplicationServer *)arg1 client:(id <FBSystemServiceClient>)arg2 fetchIconOrderForVehicleId:(NSString *)arg3 withCompletion:(void (^)(NSDictionary *))arg4;
@end

