//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SBApplication;

@interface SBApplicationActivationAssertion : NSObject
{
    SBApplication *_app;
    NSString *_name;
}

@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) SBApplication *application; // @synthesize application=_app;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithApplication:(id)arg1 name:(id)arg2;

@end

