//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class SBWallpaperEffectView, _UIBackdropView;

@interface SBAppResizingBlurContainerView : UIView
{
    SBWallpaperEffectView *_wallpaperEffectView;
    UIView *_appSnapshotView;
    _UIBackdropView *_blurView;
}

@property(retain, nonatomic) _UIBackdropView *blurView; // @synthesize blurView=_blurView;
@property(retain, nonatomic) UIView *appSnapshotView; // @synthesize appSnapshotView=_appSnapshotView;
@property(retain, nonatomic) SBWallpaperEffectView *wallpaperEffectView; // @synthesize wallpaperEffectView=_wallpaperEffectView;
- (void).cxx_destruct;
- (void)layoutSubviews;

@end

