//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView;

@interface SBAppSwitcherSoftOutlineShadowView : UIView
{
    UIView *_clippingView;
    UIImageView *_shadowImageView;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
@property(nonatomic) struct CGRect clippingFrame;
@property(nonatomic) double clippingCornerRadius;
@property(nonatomic) _Bool shouldClip;
- (id)initWithFrame:(struct CGRect)arg1;

@end

