//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBIdleTimer-Protocol.h"
#import "SBUserEventInterfaceObserver-Protocol.h"

@class NSString, SBUserEventInterface;
@protocol SBIdleTimerDelegate;

@interface SBAutomaticIdleTimer : NSObject <SBUserEventInterfaceObserver, SBIdleTimer>
{
    id <SBIdleTimerDelegate> _delegate;
    SBUserEventInterface *_userEventTimer;
    double _interval;
    long long _mode;
    _Bool _shouldReportUserEvents;
}

@property(nonatomic) __weak id <SBIdleTimerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)idleTimerForExtension;
- (_Bool)isEqualToTimer:(id)arg1;
- (void)reset;
- (void)userEventTimerReceivedUserEvent:(id)arg1;
- (void)userEventTimerPresenceTriggered:(id)arg1;
- (void)userEventTimerPresenceExpired:(id)arg1;
- (void)userEventTimerUserUnidled:(id)arg1;
- (void)userEventTimerUserIdled:(id)arg1;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (id)initWithMode:(long long)arg1 interval:(double)arg2 reportUserEvents:(_Bool)arg3 userEventInterface:(id)arg4;
- (id)initWithMode:(long long)arg1 interval:(double)arg2 reportUserEvents:(_Bool)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

