//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBAwayListItem.h"

@class NSString, SBSCardItem, UIImage;

@interface SBAwayCardListItem : SBAwayListItem
{
    SBSCardItem *_cardItem;
    UIImage *_cardThumbnail;
    UIImage *_iconImage;
}

@property(retain, nonatomic) UIImage *iconImage; // @synthesize iconImage=_iconImage;
@property(retain, nonatomic) UIImage *cardThumbnail; // @synthesize cardThumbnail=_cardThumbnail;
@property(copy, nonatomic) SBSCardItem *cardItem; // @synthesize cardItem=_cardItem;
- (void).cxx_destruct;
@property(readonly, nonatomic) __weak NSString *body;
@property(readonly, nonatomic) __weak NSString *title;
- (_Bool)inertWhenLocked;
- (id)sortDate;

@end

