//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBPanSystemGestureRecognizer.h"

@protocol SBBannerDismissSystemGestureRecognizerDelegate;

@interface SBBannerDismissSystemGestureRecognizer : SBPanSystemGestureRecognizer
{
}

- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

// Remaining properties
@property(nonatomic) __weak id <SBBannerDismissSystemGestureRecognizerDelegate> delegate; // @dynamic delegate;

@end

