//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITapGestureRecognizer.h>

@interface SBBannerTapGestureRecognizer : UITapGestureRecognizer
{
    CDUnknownBlockType _touchesBeganBlock;
    CDUnknownBlockType _touchesEndedBlock;
}

@property(copy, nonatomic) CDUnknownBlockType touchesEndedBlock; // @synthesize touchesEndedBlock=_touchesEndedBlock;
@property(copy, nonatomic) CDUnknownBlockType touchesBeganBlock; // @synthesize touchesBeganBlock=_touchesBeganBlock;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;

@end

