//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBBaseSoftwareUpdateAlertItem.h"

@interface SBBaseSoftwareUpdateInstallFailureAlertItem : SBBaseSoftwareUpdateAlertItem
{
    _Bool _actionTaken;
}

@property(nonatomic) _Bool actionTaken; // @synthesize actionTaken=_actionTaken;
- (_Bool)allowInSetup;
- (void)willDeactivateForReason:(int)arg1;

@end

