//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBBannerGestureHandler.h"

@interface SBBannerToNotificationCenterGestureHandler : SBBannerGestureHandler
{
    _Bool _canPullDown;
    _Bool _didPreparePullDown;
    struct CGSize _rootSize;
    struct CGSize _pullDownSize;
    struct CGRect _pullDownTargetRect;
    double _bannerHeight;
    _Bool _bannerHidden;
    _Bool _shouldObscure;
}

- (void)_updateWithDisplacement:(double)arg1 velocity:(double)arg2;
- (_Bool)handleGestureType:(long long)arg1 state:(long long)arg2 location:(struct CGPoint)arg3 displacement:(double)arg4 velocity:(double)arg5;

@end

