//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray;
@protocol SBBannerButtonViewControllerDelegate;

@interface SBBannerButtonViewController : UIViewController
{
    NSArray *_buttons;
    id <SBBannerButtonViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <SBBannerButtonViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_buttonPressed:(id)arg1;
- (id)_buttonForActionTitle:(id)arg1;
- (id)_buttonView;
- (struct CGSize)preferredContentSize;
- (void)setButtonTitles:(id)arg1;
- (void)loadView;

@end

