//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;

@interface SBBluetoothAccessoryBatteryMonitor : NSObject
{
    NSMutableSet *_accessoryNamesInLowPower;
}

- (void).cxx_destruct;
- (id)descriptionBuilder;
- (id)description;
- (void)dealloc;
- (void)_popLowPowerAlertForAccessoryIfNecessary:(id)arg1;
- (id)init;

@end

