//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBLeafIcon.h"

@class NSURL, SBBookmark, UIWebClip;

@interface SBBookmarkIcon : SBLeafIcon
{
    SBBookmark *_bookmark;
}

@property(readonly, nonatomic) SBBookmark *bookmark; // @synthesize bookmark=_bookmark;
- (void).cxx_destruct;
- (_Bool)isBookmarkIcon;
- (id)folderFallbackTitle;
- (id)folderTitleOptions;
- (id)matchedWebApplication;
@property(readonly, nonatomic) NSURL *launchURL;
@property(readonly, nonatomic) UIWebClip *webClip;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithBookmark:(id)arg1;

@end

