//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBTestRecipe-Protocol.h"

@class NSArray, NSString;

@interface SBBulletinTourRecipe : NSObject <SBTestRecipe>
{
    NSArray *_tour;
    unsigned long long _currentStop;
    _Bool _failedToLoadTour;
}

+ (id)title;
- (void).cxx_destruct;
- (void)loadTourFromPrefsIfNecessary;
- (void)handleVolumeDecrease;
- (void)handleVolumeIncrease;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

