//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBBulletinAlertHandlerRegistry-Protocol.h"
#import "_UISettingsKeyObserver-Protocol.h"

@class NSMutableDictionary, NSString, SBAlertItemsSettings;

@interface SBBulletinAlertHandlerRegistry : NSObject <_UISettingsKeyObserver, SBBulletinAlertHandlerRegistry>
{
    NSMutableDictionary *_handlersBySectionID;
    SBAlertItemsSettings *_settings;
    _Bool _disabled;
}

- (void).cxx_destruct;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)addAlertHandler:(id)arg1 forSection:(id)arg2;
- (id)alertHandlersForSection:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

