//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBIconModel.h"

@class NSArray;

@interface SBCarPlayIconModel : SBIconModel
{
    NSArray *_hiddenBundleIdentifiers;
    struct CGRect _screenBounds;
}

@property(nonatomic) struct CGRect screenBounds; // @synthesize screenBounds=_screenBounds;
@property(retain, nonatomic) NSArray *hiddenBundleIdentifiers; // @synthesize hiddenBundleIdentifiers=_hiddenBundleIdentifiers;
- (void).cxx_destruct;
- (void)resetCurrentIconState;
- (id)exportStateForCarKit;
- (_Bool)importState:(id)arg1;
- (void)didUnarchiveMetadata:(id)arg1;
- (id)iconModelMetadata;
- (_Bool)isIconVisible:(id)arg1;
@property(readonly, nonatomic) unsigned long long columnCount;
@property(readonly, nonatomic) unsigned long long rowCount;

@end

