//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSSet;

@interface SBComposedWallpaperSpecificationLayer : NSObject
{
}

@property(readonly, copy, nonatomic) NSDictionary *propertyListRepresentation;
@property(readonly, copy, nonatomic) NSSet *referencedAssetURLs;
- (id)initWithLayerDictionary:(id)arg1;

@end

