//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBCrossfadeZoomSettings.h"

@class SBAnimationSettings;

@interface SBCrossfadeAppTransitionSettings : SBCrossfadeZoomSettings
{
    SBAnimationSettings *_iconBlurSettings;
    SBAnimationSettings *_appSnapshotBlurSettings;
    SBAnimationSettings *_appSnapshotCornerRadiusSettings;
}

+ (id)settingsControllerModule;
@property(retain) SBAnimationSettings *appSnapshotCornerRadiusSettings; // @synthesize appSnapshotCornerRadiusSettings=_appSnapshotCornerRadiusSettings;
@property(retain) SBAnimationSettings *appSnapshotBlurSettings; // @synthesize appSnapshotBlurSettings=_appSnapshotBlurSettings;
@property(retain) SBAnimationSettings *iconBlurSettings; // @synthesize iconBlurSettings=_iconBlurSettings;
- (void).cxx_destruct;
- (void)setDefaultValues;

@end

