//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBDashBoardAppearanceProviding-Protocol.h"
#import "SBDashBoardBehaviorProviding-Protocol.h"
#import "SBDashBoardEventHandling-Protocol.h"
#import "SBDashBoardParticipating-Protocol.h"
#import "SBDashBoardPresentationProviding-Protocol.h"

@protocol SBDashBoardViewPresenting;

@protocol SBDashBoardViewControlling <SBDashBoardAppearanceProviding, SBDashBoardBehaviorProviding, SBDashBoardPresentationProviding, SBDashBoardEventHandling, SBDashBoardParticipating>
@property(readonly, nonatomic) long long presentationAltitude;
@property(readonly, nonatomic) long long presentationPriority;
@property(readonly, nonatomic) long long presentationTransition;
@property(readonly, nonatomic) long long presentationType;
@property(readonly, nonatomic) long long presentationStyle;
@property(nonatomic) __weak id <SBDashBoardViewPresenting> presenter;
@end

