//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBDashBoardEventHandling-Protocol.h"

@class NSString;

@interface SBDashBoardBlockEventHandler : NSObject <SBDashBoardEventHandling>
{
    CDUnknownBlockType _buttonPredicate;
    CDUnknownBlockType _eventBlock;
}

- (void).cxx_destruct;
- (_Bool)wouldHandleButtonEvent:(id)arg1;
- (_Bool)handleEvent:(id)arg1;
- (id)initWithButtonPredicate:(CDUnknownBlockType)arg1 eventBlock:(CDUnknownBlockType)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

