//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, SBDashBoardViewController, SBLockScreenUnlockRequest;

@protocol SBDashBoardViewControllerDelegate <NSObject>
- (void)dashBoardViewController:(SBDashBoardViewController *)arg1 unlockWithRequest:(SBLockScreenUnlockRequest *)arg2 completion:(void (^)(_Bool))arg3;
- (void)dashBoardViewController:(SBDashBoardViewController *)arg1 requestsTouchIDDisabled:(_Bool)arg2 forReason:(NSString *)arg3;
- (void)dashBoardViewControllerIrisPlayingDidFinish:(SBDashBoardViewController *)arg1;
@end

