//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIPageControl.h>

@class NSMutableArray, _UILegibilitySettings;

@interface SBDashBoardPageControl : UIPageControl
{
    _UILegibilitySettings *_sbLegibilitySettings;
    NSMutableArray *_legibilityViews;
    _Bool _cameraPageEnabled;
}

+ (struct CGSize)defaultSize;
@property(nonatomic, getter=isCameraPageEnabled) _Bool cameraPageEnabled; // @synthesize cameraPageEnabled=_cameraPageEnabled;
- (void).cxx_destruct;
- (double)_indicatorSpacing;
- (struct CGRect)_modernBounds;
- (void)_transitionIndicator:(id)arg1 toEnabled:(_Bool)arg2 index:(long long)arg3;
- (id)_indicatorViewEnabled:(_Bool)arg1 index:(long long)arg2;
- (id)_currentPageIndicatorColor;
- (id)_pageIndicatorColor;
- (id)_pageIndicatorImage:(_Bool)arg1;
- (id)_cameraIndicatorImage:(_Bool)arg1;
- (void)_setIndicatorImage:(id)arg1 toEnabled:(_Bool)arg2 index:(long long)arg3;
- (void)_updateLegibilityViews;
- (void)setLegibilitySettings:(id)arg1;
- (struct CGSize)sizeForNumberOfPages:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

