//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBApplicationHosting-Protocol.h"
#import "SBDashBoardViewPresenting-Protocol.h"

@class _UILegibilitySettings;
@protocol SBDashBoardViewControllerProtocol;

@protocol SBDashBoardPageViewControllerProtocol <SBDashBoardViewPresenting, SBApplicationHosting>
+ (unsigned long long)requiredCapabilities;
+ (_Bool)isAvailableForConfiguration;
@property(readonly, nonatomic) _Bool authenticated;
@property(nonatomic, getter=isTransitioning) _Bool transitioning;
@property(nonatomic) __weak id <SBDashBoardViewControllerProtocol> dashBoardViewController;

@optional
- (void)updateLegibilityForSettings:(_UILegibilitySettings *)arg1;
@end

