//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SBUIBannerView-Protocol.h"
#import "SBVibrantBannerView-Protocol.h"

@class NSString, SBDefaultBannerTextView, SBUIBannerContext, UIImageView;
@protocol SBDefaultBannerViewSource;

@interface SBDefaultBannerView : UIView <SBUIBannerView, SBVibrantBannerView>
{
    SBUIBannerContext *_context;
    id <SBDefaultBannerViewSource> _viewSource;
    UIImageView *_iconImageView;
    SBDefaultBannerTextView *_textView;
    UIImageView *_attachmentImageView;
    UIView *_secondaryContentView;
}

+ (id)defaultColorForElement:(long long)arg1;
+ (id)_defaultRelevanceDateColor;
- (void).cxx_destruct;
- (void)setColor:(id)arg1 forElement:(long long)arg2;
- (id)colorForElement:(long long)arg1;
- (void)_setRelevanceDateColor:(id)arg1;
- (id)_relevanceDateColor;
- (double)_secondaryContentInsetY;
- (double)_textInsetX;
- (double)_iconInsetY;
- (struct CGRect)_secondaryContentFrameForBounds:(struct CGRect)arg1;
- (struct CGRect)_secondaryContentFrame;
- (struct CGRect)_textViewFrameForBounds:(struct CGRect)arg1;
- (struct CGRect)_textViewFrame;
- (struct CGRect)_iconImageViewFrame;
- (struct CGRect)_contentFrame;
- (struct CGRect)_contentFrameForBounds:(struct CGRect)arg1;
- (struct CGRect)_attachmentImageViewFrame;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)setPercentPulledDown:(double)arg1;
- (void)setSecondaryContentView:(id)arg1;
- (id)bannerContext;
- (_Bool)_showAttachmentPreview;
- (_Bool)_hasAttachment;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithContext:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

