//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBAppSwitcherPageView.h"

@class UIView;
@protocol SBMainAppSwitcherPageContentView;

@interface SBDeckSwitcherPageView : SBAppSwitcherPageView
{
    long long _orientation;
}

@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
- (void)setView:(id)arg1 animated:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(retain, nonatomic) UIView<SBMainAppSwitcherPageContentView> *view; // @dynamic view;

@end

