//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBWorkspaceTransaction.h"

#import "FBSynchronizedTransaction-Protocol.h"

@class NSString;
@protocol FBSynchronizedTransactionDelegate;

@interface SBExternalDisplayWorkspaceSlaveTransaction : SBWorkspaceTransaction <FBSynchronizedTransaction>
{
    id <FBSynchronizedTransactionDelegate> _synchronizationDelegate;
}

@property(nonatomic) __weak id <FBSynchronizedTransactionDelegate> synchronizationDelegate; // @synthesize synchronizationDelegate=_synchronizationDelegate;
- (void).cxx_destruct;
- (void)_doIt;
- (void)_doWork;
- (void)performSynchronizedCommit;
- (_Bool)isReadyForSynchronizedCommit;
- (void)_begin;
- (id)initWithTransitionRequest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

