//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SoftwareUpdateServices/SUDescriptor.h>

@interface SBFakeSUDescriptor : SUDescriptor
{
}

- (id)documentation;
- (_Bool)isDownloadableOverCellular;
- (_Bool)isDownloadable;
- (int)updateType;
- (unsigned long long)installationSize;
- (unsigned long long)preparationSize;
- (unsigned long long)downloadSize;
- (id)productBuildVersion;
- (id)productVersion;
- (id)productSystemName;
- (id)humanReadableUpdateName;
- (id)publisher;

@end

