//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIStatusBar.h>

@interface SBFakeStatusBarView : UIStatusBar
{
}

- (void)setOverrideBreadcrumbTitle:(id)arg1 secondaryTitle:(id)arg2;
- (void)setSnapshotOverridesWithTimeEnabled:(_Bool)arg1;

@end

