//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SBWallpaperObserver-Protocol.h"
#import "_UISettingsKeyObserver-Protocol.h"

@class NSString, SBFolderSettings, UIImageView, _UILegibilitySettings;

@interface SBFolderBackgroundView : UIView <_UISettingsKeyObserver, SBWallpaperObserver>
{
    UIImageView *_tintView;
    SBFolderSettings *_folderSettings;
    double _continuousCornerRadius;
    _UILegibilitySettings *_legibilitySettings;
}

+ (double)cornerRadiusToInsetContent;
+ (struct CGSize)folderBackgroundSize;
+ (void)warmupIfNecessary;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
- (void).cxx_destruct;
- (void)_setContinuousCornerRadius:(double)arg1;
- (void)_reduceTransparencyChanged;
- (_Bool)_hasLowQualityBackground;
- (void)_updateForHavingLowQualityBackground:(_Bool)arg1;
- (id)_tintViewBackgroundColorAtFullAlpha;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

