//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIGestureRecognizer.h>

#import "UIInteractionProgressObserver-Protocol.h"

@class NSString, UIForceStageInteractionProgress;

@interface SBForceStageInteractionGestureRecognizer : UIGestureRecognizer <UIInteractionProgressObserver>
{
    _Bool _receivedFirstInteractionProgressUpdate;
    UIForceStageInteractionProgress *_forceStageInteractionProgress;
}

@property(readonly, nonatomic) UIForceStageInteractionProgress *forceStageInteractionProgress; // @synthesize forceStageInteractionProgress=_forceStageInteractionProgress;
- (void).cxx_destruct;
- (void)interactionProgress:(id)arg1 didEnd:(_Bool)arg2;
- (void)interactionProgressDidUpdate:(id)arg1;
@property(readonly, nonatomic) double interactionProgress;
- (void)dealloc;
- (id)initWithForceStageInteractionProgress:(id)arg1 target:(id)arg2 action:(SEL)arg3;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

