//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBIconObserver-Protocol.h"

@class SBFolderIcon, SBIcon, SBIconGridImage;

@protocol SBFolderIconObserver <SBIconObserver>
- (void)folderIcon:(SBFolderIcon *)arg1 didUpdateGridImage:(SBIconGridImage *)arg2 forListIndex:(unsigned long long)arg3 forContainedIconImageUpdate:(SBIcon *)arg4;
@end

