//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBGrabberTongue;

@protocol SBGrabberTongueDelegate <NSObject>
- (_Bool)grabberTongueRequiredOutsideGrabberFreeRegion:(SBGrabberTongue *)arg1;
- (_Bool)grabberTongueRequiredForWholeEdge:(SBGrabberTongue *)arg1;
- (_Bool)grabberTongueOrPullEnabled:(SBGrabberTongue *)arg1;

@optional
- (void)grabberTongueWillPresent:(SBGrabberTongue *)arg1;
- (void)grabberTongueCanceledPulling:(SBGrabberTongue *)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueEndedPulling:(SBGrabberTongue *)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueUpdatedPulling:(SBGrabberTongue *)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueBeganPulling:(SBGrabberTongue *)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (double)grabberTongueWidthOfActiveEdge:(SBGrabberTongue *)arg1;
- (double)grabberTongueWidthOfGrabberFreeRegion:(SBGrabberTongue *)arg1;
- (double)grabberTongueCenterOnEdge:(SBGrabberTongue *)arg1;
@end

