//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBMesaUnlockTrigger.h"

@class BSTimer;

@interface SBHomeButtonPressSpeedMesaUnlockTrigger : SBMesaUnlockTrigger
{
    BSTimer *_slowPressTimer;
    _Bool _bioUnlockOccurredWhileTimerWasRunning;
    _Bool _primed;
    double _slowPressDuration;
}

@property(retain, nonatomic, getter=_slowPressTimer, setter=_setSlowPressTimer:) BSTimer *slowPressTimer; // @synthesize slowPressTimer=_slowPressTimer;
@property(nonatomic) double slowPressDuration; // @synthesize slowPressDuration=_slowPressDuration;
- (void).cxx_destruct;
- (_Bool)_isTimerRunning;
- (void)_timerFired;
- (void)_cancelTimer;
- (void)_startTimer;
- (void)fingerOff;
- (void)menuButtonDown;
- (void)screenOff;
- (_Bool)bioUnlock;
- (id)succinctDescriptionBuilder;
- (id)description;
- (id)init;

@end

