//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBSearchEtceteraMultiplexingViewController.h"

@interface SBHomeScreenPullDownSearchViewController : SBSearchEtceteraMultiplexingViewController
{
}

- (_Bool)displaysWidgets;
- (void)dismissSearchViewWithReason:(unsigned long long)arg1;
- (_Bool)directlyForwardViewSizeChanges;
- (id)displayLayoutElementIdentifier;
- (unsigned long long)defaultSearchViewDismissalReason;
- (unsigned long long)defaultSearchViewPresentationSource;
- (unsigned long long)initialPresentationMode;
- (void)viewDidLoad;
- (id)init;

@end

