//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface SBHorizontalScrollFailureTriangleView : UIView
{
    int _style;
    _Bool _pointingRight;
}

- (void)drawRect:(struct CGRect)arg1;
- (id)initWithStyle:(int)arg1 recognizer:(id)arg2 forPoint:(struct CGPoint)arg3 withMaxVerticalOffset:(double)arg4 inView:(id)arg5 pointingRight:(_Bool)arg6;

@end

