//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBReusableViewMap.h"

@interface SBIconAccessoryViewMap : SBReusableViewMap
{
}

+ (id)homescreenMap;
- (void)recycleView:(id)arg1;
- (id)viewOfClass:(Class)arg1;

@end

