//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class SBIcon, SBIconView, SBIconViewMap;

@interface SBIconOverlayDarkeningView : UIView
{
    SBIcon *_icon;
    SBIconViewMap *_iconViewMap;
    SBIconView *_iconView;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 icon:(id)arg2 viewMap:(id)arg3;

@end

