//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SBIdleTimer;

@protocol SBIdleTimerDelegate <NSObject>

@optional
- (void)idleTimerDidWarn:(id <SBIdleTimer>)arg1;
- (void)idleTimerDidReceiveUserEvent:(id <SBIdleTimer>)arg1;
- (void)idleTimerDidExpire:(id <SBIdleTimer>)arg1;
- (void)idleTimerDidRefresh:(id <SBIdleTimer>)arg1;
@end

