//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBLockScreenPlugin.h"

@interface SBInCallLockScreenPlugin : SBLockScreenPlugin
{
}

- (void)_passcodeLockedStateChanged:(id)arg1;
- (long long)_effectivePresentationStyle;
- (void)_updateCallPluginPresentationStyle;
- (void)dealloc;
- (id)init;

@end

