//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SBInfoOperation : NSObject
{
    id _operand;
    NSString *_label;
}

+ (id)operationWithOperand:(id)arg1 label:(id)arg2;
@property(readonly, nonatomic) id operand; // @synthesize operand=_operand;
- (void).cxx_destruct;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithOperand:(id)arg1 label:(id)arg2;

@end

