//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBUISettings.h"

@interface SBIrisWallpaperSettings : SBUISettings
{
    _Bool _orbCancelsScroll;
    _Bool _scrollCancelsOrb;
    _Bool _irisLoopFadesOutUI;
}

+ (id)settingsControllerModule;
@property(nonatomic) _Bool irisLoopFadesOutUI; // @synthesize irisLoopFadesOutUI=_irisLoopFadesOutUI;
@property(nonatomic) _Bool scrollCancelsOrb; // @synthesize scrollCancelsOrb=_scrollCancelsOrb;
@property(nonatomic) _Bool orbCancelsScroll; // @synthesize orbCancelsScroll=_orbCancelsScroll;
- (void)setDefaultValues;

@end

