//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;
@protocol SBLayoutElementIdentity;

@protocol SBLayoutElementIdentity <NSObject>
@property(readonly, copy, nonatomic) NSString *layoutIdentifier;
- (_Bool)hasSameIdentityAsElement:(id <SBLayoutElementIdentity>)arg1;
@end

