//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SpringBoardUI/SBAlertItem.h>

@class NSString, SBApplication;

@interface SBLaunchAlertItem : SBAlertItem
{
    SBApplication *_associatedDisplay;
    int _type;
    NSString *_bundleID;
    _Bool _isDataAlert;
    _Bool _usesCellNetwork;
}

- (void).cxx_destruct;
- (void)sendUserToSettings;
- (void)turnOffAirplaneMode;
- (void)configureForInCall;
- (void)configureForAirplaneModeNonDataAlert;
- (void)configureForAirplaneModeDataAlertOffCellular:(_Bool)arg1;
- (void)configureForAirplaneModeDataAlertOnCellular:(_Bool)arg1;
- (void)configure:(_Bool)arg1 requirePasscodeForActions:(_Bool)arg2;
- (_Bool)dismissOnLock;
- (void)_displayDeactivated:(id)arg1;
- (void)setAssociatedWithDisplay:(id)arg1;
- (void)dealloc;
- (id)initWithLaunchAlertType:(int)arg1 dataAlert:(_Bool)arg2 usesCellNetwork:(_Bool)arg3 bundleID:(id)arg4;

@end

