//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBDashBoardExternalEventHandling-Protocol.h"
#import "SBLiftToWakeObserver-Protocol.h"

@class NSString, SBBacklightController, SBLiftToWakeController, SBLockScreenManager, SBPolicyAggregator;

@interface SBLiftToWakeManager : NSObject <SBDashBoardExternalEventHandling, SBLiftToWakeObserver>
{
    SBLiftToWakeController *_liftToWakeController;
    SBLockScreenManager *_accessor_lockScreenManager;
    SBBacklightController *_accessor_backlightController;
    SBPolicyAggregator *_accessor_policyAggregator;
    _Bool _gestureWokeScreen;
    _Bool _observing;
    _Bool _significantUserInteractionOccuredSinceWake;
}

@property(nonatomic, getter=_gestureWokeScreen, setter=_setGestureWokeScreen:) _Bool gestureWokeScreen; // @synthesize gestureWokeScreen=_gestureWokeScreen;
@property(retain, nonatomic, getter=_backlightController, setter=_setBacklightController:) SBBacklightController *backlightController; // @synthesize backlightController=_accessor_backlightController;
@property(retain, nonatomic, getter=_lockScreenManager, setter=_setLockScreenManager:) SBLockScreenManager *lockScreenManager; // @synthesize lockScreenManager=_accessor_lockScreenManager;
@property(retain, nonatomic, getter=_policyAggregator, setter=_setPolicyAggregator:) SBPolicyAggregator *policyAggregator; // @synthesize policyAggregator=_accessor_policyAggregator;
@property(retain, nonatomic, getter=_liftToWakeController, setter=_setLiftToWakeController:) SBLiftToWakeController *liftToWakeController; // @synthesize liftToWakeController=_liftToWakeController;
- (void).cxx_destruct;
- (_Bool)wouldHandleButtonEvent:(id)arg1;
- (_Bool)handleEvent:(id)arg1;
@property(readonly, nonatomic) long long participantState;
@property(readonly, copy, nonatomic) NSString *dashBoardIdentifier;
- (void)liftToWakeController:(id)arg1 didObserveTransition:(long long)arg2;
- (_Bool)_isLockScreenIdleTimerDisabled;
- (_Bool)_isLockScreenMainPageVisible;
- (void)_ignoredTransition:(long long)arg1;
- (void)_backlightWillTurnOn:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)initWithLiftToWakeController:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

