//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBLockScreenNotificationBannerItem.h"

@class SBUISound;

@interface SBLockScreenNotificationBulletinBannerItem : SBLockScreenNotificationBannerItem
{
    SBUISound *_sound;
}

- (void).cxx_destruct;
- (id)_bulletinListItem;
- (id)lockScreenActionContext;
- (id)attachmentImage;
- (id)attachmentText;
- (id)iconImage;
- (id)sourceDate;
- (id)message;
- (id)subtitle;
- (id)title;
- (id)sound;
- (id)initWithListItem:(id)arg1;

@end

