//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBLockScreenBulletinCell.h"

#import "SBDateLabelDelegate-Protocol.h"

@class SBSnoozedAlarmDateLabel;

@interface SBLockScreenSnoozedAlarmCell : SBLockScreenBulletinCell <SBDateLabelDelegate>
{
    SBSnoozedAlarmDateLabel *_countdownLabel;
}

+ (_Bool)wantsUnlockActionText;
+ (double)rowHeight;
- (void).cxx_destruct;
- (void)dateLabelDidChange:(id)arg1;
- (void)setContentAlpha:(double)arg1;
- (void)setFireDate:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;

@end

