//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSError, NSString;

@protocol SBLoginAppSceneHosterDelegate
- (void)sceneUpdatedRotationMode:(long long)arg1;
- (void)sceneUpdatedStatusBarUserName:(NSString *)arg1;
- (void)sceneUpdatedIdleTimerMode:(long long)arg1;
- (void)sceneDeactivatedWithError:(NSError *)arg1;
@end

