//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBAuthenticationFeedback, SBLockScreenMesaCoordinator;

@protocol SBLockScreenMesaCoordinatorDelegate <NSObject>
- (_Bool)mesaCoordinator:(SBLockScreenMesaCoordinator *)arg1 requestsUnlockWithIntent:(int)arg2;
- (_Bool)mesaCoordinator:(SBLockScreenMesaCoordinator *)arg1 requestsAuthenticationFeedback:(SBAuthenticationFeedback *)arg2;
@end

