//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBLockScreenActionHandler-Protocol.h"

@class SBLockScreenActionContext, SBLockScreenNotificationCell, SBLockScreenNotificationListView, UIScrollView;

@protocol SBLockScreenNotificationViewDelegate <SBLockScreenActionHandler>
- (void)noteListViewReadyForModelUpdate;
- (void)listView:(SBLockScreenNotificationListView *)arg1 cellDidEndScrolling:(SBLockScreenNotificationCell *)arg2;
- (void)listView:(SBLockScreenNotificationListView *)arg1 cellDidBeginScrolling:(SBLockScreenNotificationCell *)arg2;
- (void)listViewDidEndScrolling:(SBLockScreenNotificationListView *)arg1;
- (void)listViewDidBeginScrolling:(SBLockScreenNotificationListView *)arg1;
- (UIScrollView *)lockScreenScrollView;
- (void)noteUnlockActionChanged:(SBLockScreenActionContext *)arg1;
@end

