//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBLockScreenPluginAction;
@protocol SBLockScreenPluginAppearance, SBLockScreenPluginController;

@protocol SBLockScreenPluginAgent <NSObject>
- (_Bool)pluginController:(id <SBLockScreenPluginController>)arg1 sendAction:(SBLockScreenPluginAction *)arg2;
- (void)pluginController:(id <SBLockScreenPluginController>)arg1 updateAppearance:(id <SBLockScreenPluginAppearance>)arg2;
- (void)deactivatePluginController:(id <SBLockScreenPluginController>)arg1;
- (void)activatePluginController:(id <SBLockScreenPluginController>)arg1;
@end

