//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBLockOverlayContext.h"

@interface SBLockScreenPluginOverlayContext : SBLockOverlayContext
{
    long long _overlayStyle;
    _Bool _disabledMesaMatching;
}

@property(nonatomic) _Bool disabledMesaMatching; // @synthesize disabledMesaMatching=_disabledMesaMatching;
- (id)initWithPlugin:(id)arg1 lockScreenViewController:(id)arg2;

@end

