//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, SBAwayBulletinListItem, UIScrollView;
@protocol SBCoordinatedPresenting;

@protocol SBLockScreenNotificationListDelegate <NSObject>
- (void)authenticateForNotificationActionWithCompletion:(void (^)(_Bool))arg1;
- (void)addCoordinatedPresentingController:(id <SBCoordinatedPresenting>)arg1;
- (void)removeCoordinatedPresentingController:(id <SBCoordinatedPresenting>)arg1;
- (void)dismissFullscreenBulletinAlertWithItem:(SBAwayBulletinListItem *)arg1 reason:(NSString *)arg2;
- (void)modifyFullscreenBulletinAlertWithItem:(SBAwayBulletinListItem *)arg1;
- (void)presentFullscreenBulletinAlertWithItem:(SBAwayBulletinListItem *)arg1;
- (UIScrollView *)lockScreenScrollView;
- (void)notificationListBecomingVisible:(_Bool)arg1;
- (void)attemptToUnlockUIFromNotification;
- (void)bannerEnablementChanged;
@end

