//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBLockScreenPluginTransitionFactory : NSObject
{
}

+ (_Bool)_shouldAnimateTransitionFromPlugin:(id)arg1 toPlugin:(id)arg2;
+ (id)transitionFromPlugin:(id)arg1 toPlugin:(id)arg2 lockScreenViewController:(id)arg3;

@end

