//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SBLockScreenPlugin, SBLockScreenViewControllerBase;

@interface SBLockScreenPluginTransition : NSObject
{
    SBLockScreenPlugin *_fromPlugin;
    SBLockScreenPlugin *_toPlugin;
    SBLockScreenViewControllerBase *_viewController;
}

+ (id)transitionFromPlugin:(id)arg1 toPlugin:(id)arg2 viewController:(id)arg3;
@property(readonly, nonatomic) SBLockScreenViewControllerBase *viewController; // @synthesize viewController=_viewController;
@property(readonly, nonatomic) SBLockScreenPlugin *toPlugin; // @synthesize toPlugin=_toPlugin;
@property(readonly, nonatomic) SBLockScreenPlugin *fromPlugin; // @synthesize fromPlugin=_fromPlugin;
- (void).cxx_destruct;
- (void)_addToView;
- (void)_removeFromView;
- (void)_removeViewFromHierarchy:(id)arg1;
- (void)beginTransition;
- (id)initWithFromPlugin:(id)arg1 toPlugin:(id)arg2 viewController:(id)arg3;

@end

