//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBLockOverlayViewController.h"

@class NSString, SBFDeviceBlockTimer;

@interface SBLockScreenDeviceBlockViewController : SBLockOverlayViewController
{
    SBFDeviceBlockTimer *_blockTimer;
}

@property(retain, nonatomic) SBFDeviceBlockTimer *blockTimer; // @synthesize blockTimer=_blockTimer;
- (void).cxx_destruct;
- (void)start;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
@property(readonly, nonatomic) __weak NSString *slideToUnlockText;
- (void)dealloc;

@end

