//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBBestAppSuggestion, SBDisplayItem;
@protocol SBMainAppSwitcherContentViewControlling;

@protocol SBMainAppSwitcherContentViewControllerDelegate <NSObject>
- (void)switcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1 activatedBestAppSuggestion:(SBBestAppSuggestion *)arg2;
- (_Bool)switcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1 canDeleteItem:(SBDisplayItem *)arg2;
- (void)switcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1 deletedItem:(SBDisplayItem *)arg2;
- (void)switcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1 selectedItem:(SBDisplayItem *)arg2;
@end

