//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SBWindowSelfHostWrapper;

@interface SBMainAlertHostedAccessoryWrapper : NSObject
{
    _Bool _canAppearUnderAlert;
    SBWindowSelfHostWrapper *_windowHostWrapper;
}

@property(nonatomic) _Bool canAppearUnderAlert; // @synthesize canAppearUnderAlert=_canAppearUnderAlert;
@property(retain, nonatomic) SBWindowSelfHostWrapper *windowHostWrapper; // @synthesize windowHostWrapper=_windowHostWrapper;
- (void).cxx_destruct;

@end

