//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBAuthenticationFeedback, SBLockScreenUnlockRequest;
@protocol SBMesaUnlockBehavior;

@protocol SBMesaUnlockBehaviorDelegate <NSObject>
- (_Bool)mesaUnlockBehavior:(id <SBMesaUnlockBehavior>)arg1 requestsUnlock:(SBLockScreenUnlockRequest *)arg2 withFeedback:(SBAuthenticationFeedback *)arg3;
- (_Bool)mesaUnlockBehavior:(id <SBMesaUnlockBehavior>)arg1 requestsFeedback:(SBAuthenticationFeedback *)arg2;
@end

