//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface SBNotificationSeparatorView : UIView
{
    double _height;
}

+ (long long)blendMode;
+ (id)color;
+ (id)separatorForCurrentState;
+ (long long)separatorViewModeForCurrentState;
+ (id)separatorWithScreenScale:(double)arg1 mode:(long long)arg2;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)updateForCurrentState;
- (id)initWithFrame:(struct CGRect)arg1 mode:(long long)arg2;

@end

