//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SBBulletinActionHandler-Protocol.h"
#import "SBModeViewControllerDelegate-Protocol.h"

@class NSSet, NSString, SBModeViewController, SBNotificationSeparatorView, SBNotificationsViewController;
@protocol SBBulletinActionHandler;

@interface SBNotificationCenterLayoutViewController : UIViewController <SBBulletinActionHandler, SBModeViewControllerDelegate>
{
    long long _supportedNotificationCenterLayoutModes;
    long long _lastPresentedNotificationCenterLayoutMode;
    SBNotificationSeparatorView *_topSeparatorView;
    id <SBBulletinActionHandler> _bulletinActionHandler;
    SBNotificationsViewController *_notificationsViewController;
    SBModeViewController *_modeViewController;
}

@property(readonly, nonatomic) SBModeViewController *modeViewController; // @synthesize modeViewController=_modeViewController;
@property(readonly, nonatomic) SBNotificationsViewController *notificationsViewController; // @synthesize notificationsViewController=_notificationsViewController;
@property(nonatomic) __weak id <SBBulletinActionHandler> bulletinActionHandler; // @synthesize bulletinActionHandler=_bulletinActionHandler;
- (void).cxx_destruct;
- (void)runScrollTest:(id)arg1 iterations:(long long)arg2 delta:(long long)arg3 useAAGView:(_Bool)arg4;
- (_Bool)handleAction:(id)arg1 forBulletin:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (struct UIEdgeInsets)contentInsetsForModeViewController:(id)arg1;
- (void)_backgroundContrastDidChange:(id)arg1;
@property(readonly, copy, nonatomic) NSSet *visibleContentViewControllers;
- (void)viewWillLayoutSubviews;
- (long long)_notificationCenterLayoutModeForCurrentState;
- (void)_layoutModeViewController;
- (long long)layoutMode;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)_loadContentViewControllers;
- (_Bool)_needsLayoutAfterLoadingContentViewControllers;
- (_Bool)_areNotificationsViewControllersAvailable;
- (_Bool)_isDeviceMoreThanUILocked;
- (id)_notificationsViewControllerCreateIfNecessary:(_Bool)arg1;
- (void)_setUpColumnViewController:(id)arg1;
- (_Bool)_shouldLayoutInTwoColumnsInActiveLayoutMode;
- (_Bool)_shouldLayoutInTwoColumnsInLayoutMode:(long long)arg1;
- (_Bool)_managesTwoColumns;
- (id)_localizableTitleForColumnViewController:(id)arg1;
- (id)initForNotificationCenterLayoutMode:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

