//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBBulletinActionHandler-Protocol.h"

@protocol SBNotificationCenterViewControllerDelegate <SBBulletinActionHandler>
- (void)dismissPartialPulldownSpotlightAnimated:(_Bool)arg1 completion:(void (^)(void))arg2;
- (_Bool)shouldPinViewsForPartialPulldown;
- (_Bool)shouldAllowPartialPulldownForCurrentTransition;
- (_Bool)shouldClipContentView;
@end

