//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SBControlColorSettings;

@interface SBNotificationControlColorSettings : NSObject
{
    SBControlColorSettings *_vibrantSettings;
    SBControlColorSettings *_overlaySettings;
}

+ (id)settingsWithGraphicsQuality:(long long)arg1;
+ (id)actionButtonSettingsWithGraphicsQuality:(long long)arg1;
+ (id)editButtonSettingsWithGraphicsQuality:(long long)arg1;
@property(readonly, nonatomic) SBControlColorSettings *overlaySettings; // @synthesize overlaySettings=_overlaySettings;
@property(readonly, nonatomic) SBControlColorSettings *vibrantSettings; // @synthesize vibrantSettings=_vibrantSettings;
- (void).cxx_destruct;
- (id)initWithVibrantSettings:(id)arg1 overlaySettings:(id)arg2;

@end

