//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, UIView;
@protocol SBPowerDownViewInterface;

@protocol SBPowerDownViewDelegate
- (void)powerDownView:(UIView<SBPowerDownViewInterface> *)arg1 incrementValueForAggdKey:(NSString *)arg2;
- (void)powerDownViewAnimateOutCompleted:(UIView<SBPowerDownViewInterface> *)arg1;
- (void)powerDownViewRequestPowerDown:(UIView<SBPowerDownViewInterface> *)arg1;
- (void)powerDownViewRequestCancel:(UIView<SBPowerDownViewInterface> *)arg1;
@end

