//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIGestureRecognizer, UITouch;
@protocol SBCoordinatedPresenting;

@protocol SBPresentingDelegate <NSObject>
- (void)presentingControllerDidFinishPresentation:(id <SBCoordinatedPresenting>)arg1;
- (void)presentingController:(id <SBCoordinatedPresenting>)arg1 willHandleGesture:(UIGestureRecognizer *)arg2;
- (_Bool)presentingController:(id <SBCoordinatedPresenting>)arg1 gestureRecognizerShouldBegin:(UIGestureRecognizer *)arg2;
- (_Bool)presentingController:(id <SBCoordinatedPresenting>)arg1 gestureRecognizer:(UIGestureRecognizer *)arg2 shouldReceiveTouch:(UITouch *)arg3;

@optional
- (void)presentingController:(id <SBCoordinatedPresenting>)arg1 conflictingGestureDidEnd:(UIGestureRecognizer *)arg2;
- (void)presentingController:(id <SBCoordinatedPresenting>)arg1 conflictingGestureDidBegin:(UIGestureRecognizer *)arg2;
@end

