//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBVolumePressBandit-Protocol.h"
#import "_UISettingsKeyObserver-Protocol.h"

@class NSArray, NSString, PTSettingsController, SBPrototypingDefaults, SBRootSettings, UIWindow, _SBFallbackSettingsHelper;
@protocol SBTestRecipe;

@interface SBPrototypeController : NSObject <SBVolumePressBandit, _UISettingsKeyObserver>
{
    SBPrototypingDefaults *_prototypingDefaults;
    SBRootSettings *_rootSettings;
    UIWindow *_settingsWindow;
    PTSettingsController *_settingsController;
    _SBFallbackSettingsHelper *_fallbackHelper;
    NSArray *_testRecipeClassNames;
    id <SBTestRecipe> _activeTestRecipe;
    _Bool _showingSettings;
    _Bool _hasPreviousSettings;
    _Bool _showingSettingsForFallback;
    _Bool _hasActiveEventRouters;
    _Bool _isEnabled;
}

+ (void)migrateSettings;
+ (id)sharedInstance;
@property(retain, nonatomic) id <SBTestRecipe> activeTestRecipe; // @synthesize activeTestRecipe=_activeTestRecipe;
@property(readonly, nonatomic) SBRootSettings *rootSettings; // @synthesize rootSettings=_rootSettings;
@property(readonly, nonatomic, getter=isShowingSettingsUI) _Bool showingSettingsUI; // @synthesize showingSettingsUI=_showingSettings;
@property(readonly, nonatomic, getter=isPrototypingEnabled) _Bool prototypingEnabled; // @synthesize prototypingEnabled=_isEnabled;
- (void).cxx_destruct;
- (void)_updateEventRouters;
- (void)_updatePreventingLockover;
- (void)_changeActiveTestRecipeIfNecessary;
- (void)_tearDownSettingsWindow;
- (struct CGRect)_offscreenFrame;
- (void)_hideSettings;
- (void)showSettingsForFallback;
- (void)_maybeToggleEnablement;
- (void)_showSettings;
- (id)_testRecipeClassNames;
- (_Bool)_restorePreviousSettings;
- (_Bool)_hasPreviousSettings;
- (void)_save;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)handleVolumeDecrease;
- (void)handleVolumeIncrease;
- (_Bool)handleKeyHIDEvent:(struct __IOHIDEvent *)arg1;
- (void)showOrHide;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

