//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface SBRebootContext : NSObject <NSCopying>
{
    NSString *_reason;
    _Bool _isDark;
    _Bool _fromOTASoftwareUpdate;
}

@property(nonatomic, getter=isDark) _Bool dark; // @synthesize dark=_isDark;
@property(copy, nonatomic) NSString *reason; // @synthesize reason=_reason;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)initWithReason:(id)arg1;

@end

