//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBHUDView.h"

@interface SBRotationLockHUDView : SBHUDView
{
    _Bool _locked;
    _Bool locked;
}

@property(nonatomic, getter=isLocked) _Bool locked; // @synthesize locked;
- (id)init;
- (void)_updateLockedImage;

@end

