//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSHashTable, NSMutableDictionary;

@interface SBScreenManager : NSObject
{
    NSHashTable *_handlers;
    NSMutableDictionary *_displayToHandlerMap;
    NSMutableDictionary *_displayToScreenMap;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)addConnectionHandler:(id)arg1;
- (void)_screenDidDisconnect:(id)arg1;
- (void)_screenDidConnect:(id)arg1;
- (void)_updateHandlerForConnectionToScreen:(id)arg1 withDisplay:(id)arg2;
- (id)init;

@end

