//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBSecureWindow.h"

@interface SBSceneLayoutWindow : SBSecureWindow
{
}

+ (_Bool)sb_autorotates;
- (long long)activeInterfaceOrientation;
- (id)_layoutController;
- (id)layoutCoordinateSpace;
- (id)referenceCoordinateSpace;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

