//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBSDisplay, SBScreenManager, UIScreen;

@protocol SBScreenConnectionHandler <NSObject>
- (void)screenManager:(SBScreenManager *)arg1 didTriggerConnectionHandlerEvent:(long long)arg2 forScreen:(UIScreen *)arg3 withDisplay:(FBSDisplay *)arg4;
- (_Bool)screenManager:(SBScreenManager *)arg1 shouldBindConnectionHandlerToScreen:(UIScreen *)arg2 withDisplay:(FBSDisplay *)arg3;
@end

