//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBSearchEtceteraIsolatedViewControllerAnimatedTransitioning-Protocol.h"

@class NSString, SBSearchBackdropView, SBSearchEtceteraLayoutView, UIView;
@protocol SBViewControllerContextTransitioning;

@interface SBSearchEtceteraBlurringTransitionAnimator : NSObject <SBSearchEtceteraIsolatedViewControllerAnimatedTransitioning>
{
    SBSearchEtceteraLayoutView *_layoutView;
    UIView *_outgoingView;
    UIView *_incomingView;
    UIView *_otherView;
    UIView *_searchView;
    UIView *_otherWrapperView;
    SBSearchBackdropView *_backdropView;
    unsigned long long _initialMode;
    id <SBViewControllerContextTransitioning> _transitionContext;
    double _percentComplete;
    unsigned long long _transitionToken;
    unsigned long long _destinationMode;
    unsigned long long _transitionStyle;
}

@property(nonatomic) unsigned long long transitionStyle; // @synthesize transitionStyle=_transitionStyle;
@property(nonatomic) unsigned long long destinationMode; // @synthesize destinationMode=_destinationMode;
- (void).cxx_destruct;
- (id)_backdropViewSettingsForStyle;
- (_Bool)_shouldAllowFullMotion;
- (unsigned long long)_searchBackdropLowQualityStyleForStyle;
- (_Bool)_shouldUseDarkTintForStyle;
- (_Bool)_shouldUseBlurForStyle;
- (void)_cleanupAfterAnimating:(_Bool)arg1;
- (void)_animateIntoSearch:(_Bool)arg1;
- (void)_prepareToAnimate;
- (_Bool)supportsRestarting;
- (double)percentComplete;
- (void)_finishInteractiveTransition:(id)arg1 withCompletionSpeed:(double)arg2 completionCurve:(long long)arg3;
- (void)finishInteractiveTransition:(id)arg1 withCompletionSpeed:(double)arg2 completionCurve:(long long)arg3;
- (void)_cancelInteractiveTransition:(id)arg1 withCompletionSpeed:(double)arg2 completionCurve:(long long)arg3;
- (void)cancelTransition:(id)arg1 withCompletionSpeed:(double)arg2 completionCurve:(long long)arg3;
- (void)updateTransition:(id)arg1 withPercentComplete:(double)arg2;
- (void)_animateInteractiveTransition:(id)arg1;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (_Bool)shouldMoveIntoSearchOnCancel;
- (_Bool)shouldMoveIntoSearch;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

