//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBDashBoardExternalEventHandling-Protocol.h"

@class NSString, SBBootDefaults, SBSoftwareUpdateController;

@interface SBSetupManager : NSObject <SBDashBoardExternalEventHandling>
{
    _Bool _inSetupMode;
    SBSoftwareUpdateController *_suController;
    SBBootDefaults *_bootDefaults;
    _Bool _fromOTASoftwareUpdate;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) _Bool fromOTASoftwareUpdate; // @synthesize fromOTASoftwareUpdate=_fromOTASoftwareUpdate;
- (void).cxx_destruct;
- (void)_clearFromOTADefault;
- (void)_showStartupAlertItemIfNecessary;
- (_Bool)_setInSetupMode:(_Bool)arg1;
- (_Bool)handleEvent:(id)arg1;
- (_Bool)wouldHandleButtonEvent:(id)arg1;
@property(readonly, nonatomic) long long participantState;
@property(readonly, copy, nonatomic) NSString *dashBoardIdentifier;
- (void)postLaunchCompleteNotificationForSetup;
- (void)showSetupLogoForSetupLaunch;
- (_Bool)setupHasFinishedRestoringFromBackup;
- (_Bool)updateInSetupMode;
@property(readonly, nonatomic, getter=isInSetupMode) _Bool inSetupMode;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

