//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBSearchEtceteraMultiplexingViewController;

@protocol SBSearchEtceteraMultiplexingViewControllerAppearanceDelegate <NSObject>

@optional
- (void)searchEtceteraViewController:(SBSearchEtceteraMultiplexingViewController *)arg1 willDismissSearchWithReason:(unsigned long long)arg2;
- (_Bool)searchEtceteraViewController:(SBSearchEtceteraMultiplexingViewController *)arg1 shouldDelaySearchWillDismissWithReason:(unsigned long long)arg2;
- (_Bool)searchEtceteraViewController:(SBSearchEtceteraMultiplexingViewController *)arg1 shouldPresentSearchFromSource:(unsigned long long)arg2;
- (void)searchEtceteraViewController:(SBSearchEtceteraMultiplexingViewController *)arg1 didChangeToMode:(unsigned long long)arg2 animated:(_Bool)arg3;
- (void)searchEtceteraViewController:(SBSearchEtceteraMultiplexingViewController *)arg1 changingToMode:(unsigned long long)arg2 animated:(_Bool)arg3;
- (void)searchEtceteraViewController:(SBSearchEtceteraMultiplexingViewController *)arg1 willChangeToMode:(unsigned long long)arg2 animated:(_Bool)arg3;
@end

