//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBSIMLockEntryAlertView.h"

@class NSString;

@interface SBSIMLockPUKEntryAlertView : SBSIMLockEntryAlertView
{
    int _state;
    NSString *_enteredPUKCode;
    NSString *_newPIN;
}

- (void).cxx_destruct;
- (void)_attemptPUKUnlock;
- (id)_pukAttemptsRemainingLabel;
- (void)_unlock;
- (void)setupFailureState;
- (void)setupSuccess;
- (id)label;
- (id)titleText;

@end

