//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBDisplayItem, SBSideSwitcherPageView, SBSideSwitcherScrollingItemViewController;

@protocol SBSideSwitcherScrollingItemViewDelegate <NSObject>
- (_Bool)sideSwitcherScroller:(SBSideSwitcherScrollingItemViewController *)arg1 displayItemWantsToBeKeptInViewHierarchy:(SBDisplayItem *)arg2;
- (double)sideSwitcherScrollerDistanceBetweenItems:(SBSideSwitcherScrollingItemViewController *)arg1;
- (struct CGSize)sideSwitcherScrollerItemSize:(SBSideSwitcherScrollingItemViewController *)arg1;
- (void)sideSwitcherScroller:(SBSideSwitcherScrollingItemViewController *)arg1 purgeView:(SBSideSwitcherPageView *)arg2;
- (SBSideSwitcherPageView *)sideSwitcherScroller:(SBSideSwitcherScrollingItemViewController *)arg1 viewForDisplayItem:(SBDisplayItem *)arg2;
@end

