//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UINavigationBar, UITextView;

@interface SBSMSClass0AboutViewController : UIViewController
{
    UITextView *_aboutContentView;
    UINavigationBar *_navigationBar;
}

- (void).cxx_destruct;
- (id)formattedAboutText;
- (void)doneButtonTapped:(id)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;

@end

