//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SUAutoInstallOperation;

@interface SBSoftwareUpdateInstallOperationLifeCycleHandler : NSObject
{
    _Bool _used;
    SUAutoInstallOperation *_tryTonightOperation;
}

@property(nonatomic) _Bool used; // @synthesize used=_used;
- (void).cxx_destruct;
- (void)_clearTryTonightOperationCancelling:(_Bool)arg1 forReason:(id)arg2;
- (void)cancel;
@property(readonly, nonatomic) SUAutoInstallOperation *tryTonightOperation; // @synthesize tryTonightOperation=_tryTonightOperation;
- (void)dealloc;
- (id)initWithTryTonightInstallOperation:(id)arg1;

@end

