//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBSoundPreferences : NSObject
{
}

+ (_Bool)shouldVibrateForCurrentRingerStateWithAudioCategory:(id)arg1;
+ (_Bool)shouldVibrateForCurrentRingerState;
+ (_Bool)vibrateWhenSilent;
+ (_Bool)vibrateWhenRinging;
+ (id)ringtonePath;
+ (id)ringtoneIdentifier;
+ (id)calendarAlarmPath;
+ (id)_soundDefaults;

@end

