//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBSoftwareUpdateInstallOptions : NSObject
{
    _Bool _automaticInstallAttempt;
    _Bool _installDark;
}

@property(nonatomic) _Bool installDark; // @synthesize installDark=_installDark;
@property(nonatomic) _Bool automaticInstallAttempt; // @synthesize automaticInstallAttempt=_automaticInstallAttempt;
- (id)description;

@end

