//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBSOSTriggerObserver;

@protocol SBSOSTriggerObserverDelegate <NSObject>
- (void)sosDidTrigger:(SBSOSTriggerObserver *)arg1 completion:(void (^)(_Bool))arg2;

@optional
- (void)sosTriggerDidBecomeInactive:(SBSOSTriggerObserver *)arg1;
- (void)sosTriggerDidBecomeActive:(SBSOSTriggerObserver *)arg1;
@end

