//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBStarkFocusMovementManager : NSObject
{
}

- (_Bool)isMovementAllowedForHeading:(unsigned long long)arg1 direction:(unsigned long long)arg2 isRTL:(_Bool)arg3 isLeftHandDrive:(_Bool)arg4;

@end

