//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIImageView, UILabel;

@interface SBStarkRelockUIViewController : UIViewController
{
    UIImageView *_imageView;
    struct CGSize _imageSize;
    UILabel *_label;
    double _labelOffset;
    struct CGSize _labelSize;
}

- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end

