//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBIconListPageControl.h"

@interface SBStarkIconListPageControl : SBIconListPageControl
{
    double _scale;
}

@property(nonatomic) double scale; // @synthesize scale=_scale;
- (double)_indicatorSpacing;
- (id)_iconListIndicatorImage:(_Bool)arg1;

@end

