//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBWorkspaceTransaction.h"

#import "SBAlertManagerObserver-Protocol.h"

@class FBDisplayLayoutTransition, NSString, SBAlertManager, SBStarkScreenController;

@interface SBStarkWorkspaceTransaction : SBWorkspaceTransaction <SBAlertManagerObserver>
{
    FBDisplayLayoutTransition *_rootLayoutTransition;
    SBStarkScreenController *_starkScreenController;
    SBAlertManager *_starkScreenAlertManager;
}

@property(readonly, nonatomic) SBStarkScreenController *starkScreenController; // @synthesize starkScreenController=_starkScreenController;
@property(readonly, nonatomic) SBAlertManager *starkScreenAlertManager; // @synthesize starkScreenAlertManager=_starkScreenAlertManager;
- (void).cxx_destruct;
- (void)_didComplete;
- (void)_willBegin;
- (void)dealloc;
- (id)initWithTransitionRequest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

