//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBFolderController.h"

@interface SBStarkFolderController : SBFolderController
{
    unsigned long long _interactionAffordances;
    _Bool _supportsKnobEvents;
    _Bool _supportsTouchEvents;
}

- (void)_configureForInnerFolderController:(id)arg1;
@property(nonatomic) unsigned long long interactionAffordances;
- (id)_iconPageIndicatorImageSetCache;
- (Class)_contentViewClass;

@end

