//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/_UIRemoteViewController.h>

#import "SBSUICarDisplayNowPlayingHostInterface-Protocol.h"
#import "SBSUICarDisplayNowPlayingInterface-Protocol.h"

@protocol SBStarkNowPlayingServiceDelegate;

@interface SBStarkNowPlayingService : _UIRemoteViewController <SBSUICarDisplayNowPlayingHostInterface, SBSUICarDisplayNowPlayingInterface>
{
    id <SBStarkNowPlayingServiceDelegate> _delegate;
}

+ (id)serviceViewControllerInterface;
+ (id)exportedInterface;
@property(nonatomic) __weak id <SBStarkNowPlayingServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)switchToState:(id)arg1;
- (void)viewServiceDidTerminateWithError:(id)arg1;

@end

