//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBIconView.h"

@interface SBStarkIconView : SBIconView
{
    _Bool _alwaysAppearsFocused;
}

+ (double)_labelHeight;
+ (struct CGSize)maxLabelSize;
+ (struct CGRect)_rectForLayoutMetric:(int)arg1;
+ (struct CGSize)defaultIconSize;
+ (struct UIEdgeInsets)minimumInterIconSpacing;
+ (struct UIEdgeInsets)iconImagePaddingInsets;
+ (_Bool)canShowLabelAccessoryView;
+ (int)_defaultIconFormat;
@property(nonatomic) _Bool alwaysAppearsFocused; // @synthesize alwaysAppearsFocused=_alwaysAppearsFocused;
- (struct CGRect)_frameForLabel;
- (void)prepareForReuse;
- (id)_labelImageParameters;
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;
- (_Bool)canBecomeFocused;

@end

