//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface SBSwitchAppList : NSObject
{
    NSArray *_list;
}

@property(retain, nonatomic) NSArray *list; // @synthesize list=_list;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)_resetList;
- (id)_findApplicationInDirection:(unsigned long long)arg1 startLookingAtIndex:(unsigned long long)arg2 inList:(id)arg3;
- (_Bool)_bundleIDShouldBeRepresentedInList:(id)arg1;
- (void)resetList;
- (_Bool)containsBundleID:(id)arg1;
- (id)applicationBundleIDBeforeBundleID:(id)arg1;
- (id)applicationBundleIDAfterBundleID:(id)arg1;
- (id)description;
- (id)init;

@end

