//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBSystemServiceServerDelegate-Protocol.h"

@class SBSystemServiceServer;
@protocol FBSystemServiceClient;

@protocol SBSystemServiceServerBiometricsDelegate <SBSystemServiceServerDelegate>
- (void)systemServiceServer:(SBSystemServiceServer *)arg1 client:(id <FBSystemServiceClient>)arg2 fetchUnlockCredentialSet:(void (^)(NSData *))arg3;
@end

