//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBLaunchAlertItem.h"

@interface SBTelephonyAirplaneModeAlertItem : SBLaunchAlertItem
{
    _Bool _wasDeviceLocked;
}

@property(nonatomic) _Bool wasDeviceLocked; // @synthesize wasDeviceLocked=_wasDeviceLocked;
- (_Bool)reappearsAfterLock;
- (_Bool)dismissOnLock;

@end

