//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBTestRecipe-Protocol.h"
#import "SBThermalWarningAlertItemDelegate-Protocol.h"

@class NSArray, NSString, SBAlertItem;

@interface SBTestableAlertItemTestRecipe : NSObject <SBThermalWarningAlertItemDelegate, SBTestRecipe>
{
    SBAlertItem *_item;
    NSArray *_recipesToTest;
}

+ (id)nameForCase:(long long)arg1;
+ (id)testCasesGrouped;
+ (id)testCases;
+ (id)title;
@property(retain, nonatomic) NSArray *recipesToTest; // @synthesize recipesToTest=_recipesToTest;
- (void).cxx_destruct;
- (id)alertForIndex:(long long)arg1;
- (id)_nextAlertItemToTest;
- (id)dataPlanAlertItemForCase:(long long)arg1;
- (id)_mapsApp;
- (id)_anySUDescriptor;
- (id)_anyLeafIcon;
- (id)_anyUserInstalledAppIcon;
- (id)_anyAppIcon;
- (void)thermalWarningAlert:(id)arg1 didTriggerAction:(int)arg2;
- (void)handleVolumeDecrease;
- (void)handleVolumeIncrease;
- (void)_dismissCurrentItem;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

