//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBTouchTemplateGestureRecognizer.h"

@interface SBTouchTemplatePinchGestureRecognizer : SBTouchTemplateGestureRecognizer
{
}

- (double)_computeHandSizeCompensationGain:(double)arg1;
- (double)_computeNonlinearSpeedGain:(double)arg1;
- (double)incrementalGestureMotionForCandidate:(id)arg1 withTransformAnalyzerInfo:(id)arg2;
- (_Bool)hasSignificantMotionToBegin;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

@end

