//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBUserEventInterface;

@protocol SBUserEventInterfaceObserver <NSObject>

@optional
- (void)userEventTimerUserUnidled:(SBUserEventInterface *)arg1;
- (void)userEventTimerUserIdled:(SBUserEventInterface *)arg1;
- (void)userEventTimerPresenceExpired:(SBUserEventInterface *)arg1;
- (void)userEventTimerPresenceTriggered:(SBUserEventInterface *)arg1;
- (void)userEventTimerReceivedUserEvent:(SBUserEventInterface *)arg1;
@end

