//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SBUserEventInterfaceObserver;

@interface SBUserEventInterface : NSObject
{
    id <SBUserEventInterfaceObserver> _observer;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_userEventReceived;
- (void)_userEventPresenceExpired;
- (void)_userEventPresenceTriggered;
- (void)_userEventsDidUnIdle;
- (void)_userEventsDidIdle;
- (int)_hidModeForMode:(long long)arg1;
- (void)callbackOnNextUserEvent;
- (void)resetWithInterval:(double)arg1 mode:(long long)arg2 observer:(id)arg3;
- (id)init;

@end

