//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIColor;

@protocol SBVibrantBannerView <NSObject>
+ (UIColor *)defaultColorForElement:(long long)arg1;
- (void)setColor:(UIColor *)arg1 forElement:(long long)arg2;
- (UIColor *)colorForElement:(long long)arg1;
@end

