//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBTransaction.h"

@class SBApplication;

@interface SBWaitForAppActivationTransaction : SBTransaction
{
    SBApplication *_application;
    _Bool _manualListener;
    _Bool _done;
}

- (void).cxx_destruct;
- (_Bool)_appStateChanged:(int)arg1;
- (void)_activationStateChanged:(id)arg1;
- (void)_didComplete;
- (void)_begin;
- (id)application;
- (void)noteActivationStateChanged:(int)arg1;
- (id)initWithApplication:(id)arg1 manualListener:(_Bool)arg2;
- (id)initWithApplication:(id)arg1;

@end

