//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBWallpaperStyleTransitionStateWrapper : NSObject
{
    CDStruct_059c2b36 _state;
}

+ (id)wrapperWithState:(CDStruct_059c2b36)arg1;
@property(nonatomic) CDStruct_059c2b36 state; // @synthesize state=_state;
- (id)description;

@end

