//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBWallpaperServer;

@protocol SBWallpaperServerDelegate <NSObject>
- (void)wallpaperServer:(SBWallpaperServer *)arg1 fetchThumbnailDataForVariant:(long long)arg2 completionHandler:(void (^)(NSData *))arg3;
@end

