//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBWalletPrearmRecognizer;

@protocol SBWalletPrearmRecognizerDelegate <NSObject>
- (void)walletPrearmRecognizer:(SBWalletPrearmRecognizer *)arg1 didFailToRecognizeForReason:(unsigned long long)arg2;
- (void)walletPrearmRecognizerDidRecognize:(SBWalletPrearmRecognizer *)arg1;
@end

