//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBApplication.h"

@class NSURL, SBBookmarkIcon;

@interface SBWebApplication : SBApplication
{
    SBBookmarkIcon *_bookmarkIcon;
    NSURL *_launchURL;
}

+ (id)_webClipIdentifierFromWebAppIdentifier:(id)arg1;
+ (id)_webAppIdentifierFromWebClipIdentifier:(id)arg1;
+ (id)_dataContainerURL;
+ (id)_snapshotDirectory;
+ (id)_snapshotManifest;
+ (id)_primaryWebAppInfo;
@property(retain, nonatomic) NSURL *launchURL; // @synthesize launchURL=_launchURL;
- (void).cxx_destruct;
- (id)_customStartupImageForLaunchingOrientation:(long long)arg1;
- (void)refreshLaunchImagesInSnapshotManifestIfNeededWithInfoDictionary:(id)arg1;
- (id)_snapshotManifest;
- (id)_baseSceneIdentifier;
- (_Bool)isWebApplication;
- (id)iconIdentifier;
- (id)sandboxPath;
- (Class)iconClass;
- (id)displayName;
@property(retain, nonatomic) SBBookmarkIcon *bookmarkIcon;

@end

