//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface SBZoomView : UIView
{
}

+ (id)_chromeStatusBarImageForInterfaceOrientation:(long long)arg1;
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;
- (id)_initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

