//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@interface UILabel (SpringBoard)
- (double)sb_yPositionForLayoutAfterLabel:(id)arg1 baselineOffset:(double)arg2;
- (double)sb_yPositionForLabelWithContainerBounds:(struct CGRect)arg1 baselineOffset:(double)arg2 font:(id)arg3;
- (double)sb_yPositionForLabelWithContainerBounds:(struct CGRect)arg1 lineHeight:(double)arg2 baselineOffset:(double)arg3 font:(id)arg4;
@end

