//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (SBAsynchronousSnapshot)
- (void)sb_generateSnapshotViewAsynchronouslyOnQueue:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)sb_generateSnapshotAsynchronouslyOnQueue:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
@end

