//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIWindow.h>

@interface UIWindow (SelfHosting)
- (id)sb_hostWrapperForUseInWindow:(id)arg1 hostRequester:(id)arg2 enable:(_Bool)arg3 orderFront:(_Bool)arg4;
- (id)sb_hostWrapperForUseInWindow:(id)arg1 hostRequester:(id)arg2;
@end

