//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDate, NSDictionary, NSString;

@protocol UNSSystemStateProviding <NSObject>
- (_Bool)shouldThrottleContentNotificationForApplicatin:(NSString *)arg1 onDate:(NSDate *)arg2 withLastCount:(unsigned long long *)arg3 onDay:(long long *)arg4;
- (_Bool)isNewsstandContentBackgroundModeSupportedForApplication:(NSString *)arg1;
- (_Bool)isNewsstandApplication:(NSString *)arg1;
- (_Bool)isRemoteNotificationBackgroundModeSupportedForApplication:(NSString *)arg1;
- (_Bool)isBackgroundAppRefreshSupportedForApplication:(NSString *)arg1;
- (_Bool)isApplicationRestricted:(NSString *)arg1;
- (_Bool)isApplicationInstalled:(NSString *)arg1;

@optional
- (void)handleContentAvailableNotificationForApplication:(NSString *)arg1 userInfo:(NSDictionary *)arg2 priority:(long long)arg3 completion:(void (^)(void))arg4;
@end

