//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UIScrollViewDelegate-Protocol.h"

@class NCMaterialSettings, NSArray, UIScrollView, UIView, WGWidgetGroupViewController;

@protocol WGWidgetGroupViewControllerDelegate <UIScrollViewDelegate>

@optional
- (NSArray *)additionalBundleIdentifiersForAttribution:(WGWidgetGroupViewController *)arg1;
- (NCMaterialSettings *)materialSettingsForWidgetGroupViewController:(WGWidgetGroupViewController *)arg1;
- (UIView *)widgetGroupViewController:(WGWidgetGroupViewController *)arg1 newCustomBackgroundViewForItem:(id)arg2 inScrollView:(UIScrollView *)arg3;
@end

